name: 'Label Stale Issues'
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8.0.0
        with:
          stale-issue-label: 'stale'
          exempt-issue-labels: 'epic'
          days-before-stale: 2
          days-before-pr-stale: -1
          days-before-close: -1
