name: Set Stale Label on Issues

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  add_stale_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set "stale" label on update
        uses: actions/github-script@v6
        with:
          script: |
            const needsStale = (issue) => {
              issue.assignees !== undefined
              && issue.assignees.length > 0
              && !contains(issue.labels.*.name, 'epic') 
              && !contains(issue.labels.*.name, 'stale') 
              && issue.state === 'open' 
              && issue.updated_at <= format_datetime(now() - duration('P15M'), '%Y-%m-%dT%H:%M:%SZ') 
            }
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            for (const issue of issues.data) {
              if (needsStale(issue)) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ['stale']
                });
              }
            }
