name: Set Stale Label on Issues

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  add_stale_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set "stale" label on update
        uses: actions/github-script@v4.2.0
        with:
          script: |
            const needsStale = async (issue) =>  {
              const labels = issue.labels.map(labelObj => labelObj.name);

              issue.assignees !== undefined
              && issue.assignees.length > 0
              && !labels.includes('epic')
              && !labels.includes('stale')
              && issue.state === 'open' 
              && issue.updated_at <= format_datetime(now() - duration('P15M'), '%Y-%m-%dT%H:%M:%SZ') 
            }
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            for (const issue of issues.data) {
              if (issue.pull_request === undefined && needsStale(issue)) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ['stale']
                });
              }
            }
